import type { NextPage } from 'next'
import Head from 'next/head'
import CardList from '../components/CardList'
import Header from '../components/Header'
import UserInput from '../components/UserInput'
import styles from '../styles/Home.module.scss'
import { defaultProfiles } from '../Utils'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <UserInput/>
      <CardList profiles={defaultProfiles}/>


     
    </div>
  )
}

export default Home
