import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import CardList from '../components/CardList'
import Header from '../components/Header'
import UserInput from '../components/UserInput'
import styles from '../styles/Home.module.scss'
import { defaultProfiles, profileType } from './Utils'


const Home: NextPage = () => {
     const [profiles, setProfiles ] = useState(defaultProfiles);
     const addCard = (newProfile: profileType) => {
      setProfiles([...profiles, newProfile]);
     }
    //  useEffect(() => {
    //             setTimeout(() => {
    //               setProfiles([...profiles, defaultProfiles[0]])
    //           }, 500);
    //  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub Cards App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <UserInput addCard={addCard}/>
      <CardList profiles={profiles}/>


     
    </div>
  )
}

export default Home
